### ISSUE TITLE
quit doesn't follow Apple Guidelines

### ISSUE THREAD

**Issue by digitaltvguy** [jvanakker/tvOSBrowser#13]
tvOS Browser currently requires MENU key be held down instead of just pressed once repeatedly to return to HOME screen.  tvOS guidelines require that repeated MENU key presses eventually returns to HOME screen

How can I modify project to make it follow the guidelines?

**Comment by jvanakker** [comment]
I am not quite sure what you request, for me a single press on “MENU” does exit the app, which seems normal behaviour amongst other tvOS apps. Could you please elaborate?

**Comment by jvanakker** [comment]
Update: you're right, the changes from the latest pull request changed that behaviour indeed. Will try to correct this.

**Comment by jvanakker** [comment]
Update: I added improvements to comply with the Apple HIG, pressing Menu will now return to the Home Screen.
Single press "Play/Pause" will now show the quick menu (including quick "Navigate back" option).
Double press "Play/Pause" will now show the advanced menu.
