### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by airelld** [jvanakker/tvOSBrowser#15]
Hi there is anyone else running into the issue that the app suddenly won’t open? I select it from the main screen and it just returns you to home screen as if the app crashed upon startup. 

Thanks-

**Comment by jvanakker** [comment]
This is correct behaviour. If you are using a free Apple developer account, so when you do **not** have a payed Apple Developer Membership, the sideloaded app will only work for a few (7?) days.

The solution in that case is to rebuild the app and run on the device through Xcode.
