### ISSUE TITLE
Build Failed on tvos 12.1.2

### ISSUE THREAD

**Issue by janelleintercom** [jvanakker/tvOSBrowser#18]
When using the files provided and attempting to build without modifying the Availability.h file, I receive the following error:

:-1: No profiles for 'com.jva.tvbrowser' were found: Xcode couldn't find any tvOS App Development provisioning profiles matching 'com.jva.tvbrowser'. (in target 'Browser')

I just downloaded Xcode so I'm on the latest version Version 10.1 (10B61)

**Comment by jvanakker** [comment]
This is because you have to change the Bundle ID to your own, and use your own provisioning profile.

To do this:
Go to the target settings, click the the project name ("Browser") in the upper left, in the left pane in Xcode: this will open the settings on the "General" tab. At "Bundle Identifier", change this to your own new unique ID.
Next, at the "Signing" section below, Xcode will notify there is no correct signing and shows a "Fix" button which will create and download your own certificate and provisioning profile.

I'll add these steps to the readme later on.

**Comment by janelleintercom** [comment]
Thanks! 

However I'm now getting the following errors:

Semantic Issue Group
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UITextView.h:60:22: 'UIDataDetectorTypes' is unavailable: not available on tvOS
/Users/janelle/Documents/tvOSBrowser/_Project/Browser/AppDelegate.h:9:9: While building module 'UIKit' imported from /Users/janelle/Documents/tvOSBrowser/_Project/Browser/AppDelegate.h:9:
/<module-includes>:1:9: In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:9:9: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitCore.h:179:9: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitCore.h:179:
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDataDetectors.h:11:32: 'UIDataDetectorTypes' has been explicitly marked unavailable here
Parse Issue Group
/Users/janelle/Documents/tvOSBrowser/_Project/Browser/AppDelegate.h:9:9: Could not build module 'UIKit'
/Users/janelle/Documents/tvOSBrowser/_Project/Browser/AppDelegate.m:9:9: In file included from /Users/janelle/Documents/tvOSBrowser/_Project/Browser/AppDelegate.m:9:

**Comment by Brio97131** [comment]
Built on TVOS 12.1.2  Jw player doesn't work on it ?

**Comment by dwattel** [comment]
I have a quistion: how can I install the build to my TV?

**Comment by pledovski** [comment]
Getting the same errors as @janelleintercom 
@jvanakker maybe have some idea how could it be fixed?
tvOS 12.2.1

**Comment by pledovski** [comment]
Also got: 
Could not build module 'UIKit'
1. In file included from /Users/hp/Documents/tvOSBrowser1/_Project/Browser/AppDelegate.m:9:

**Comment by huyvuro** [comment]
hello
I have a question
What is unique ID
Thanks

**Comment by jvanakker** [comment]
Try updating to the latest Xcode and latest version of the project.

**Comment by sasikreddi** [comment]
I fixed this issue by updating UIDocumentInteractionController.h with the following changes.
- Right click on the error and open the file location
- Copy UIDocumentInteractionController.h to Documents and edit the following
Replace "__TVOS_PROHIBITED" with "__TVOS_PROHIBITED_NOTQUITE"
Line numbers 20 and 62
20: API_AVAILABLE(ios(3.2)) __TVOS_PROHIBITED_NOTQUITE @interface UIDocumentInteractionController : NSObject <UIActionSheetDelegate>
62: API_AVAILABLE(ios(3.2)) __TVOS_PROHIBITED_NOTQUITE @protocol UIDocumentInteractionControllerDelegate <NSObject>
- Rebuild the project.
