### ISSUE TITLE
53 bugs, what do?

### ISSUE THREAD

**Issue by Dman0o9** [jvanakker/tvOSBrowser#20]
So, I've edited my Availability.h file to add the NOTQUITE thing to the end of each of the TVOS_UNAVAILABLE and TVOS_PROHBITED lines, but I saw a mention in another issue that a line in UIDataDetectors.h, namely } API_UNAVAILABLE(tvos); needed to be edited, but that line isn't even in my UIDataDetectors.h file. After adding the NOTQUITE part to my availability.h, I'm getting 53 errors, shown in the attached screenshot. Keep in mind, I'm REALLY unfamiliar with coding and Xcode and all this, so the simpler you can explain things, the better. I believe I'm on TVOS 12, if that helps. I've also seen that the availability.h file doesn't need to be edited, but I don't know if there's anything that needs to be done in its place, so I did it as a sort of better safe than sorry thing. (Yeah, this message is a mess, just ask for any details you may be confused with)
![screen shot 2019-03-03 at 8 04 09 am](https://user-images.githubusercontent.com/48182222/53697926-2dd20d80-3d8b-11e9-83ab-7363a89d3bdc.png)
![screen shot 2019-03-03 at 7 59 50 am](https://user-images.githubusercontent.com/48182222/53697927-2e6aa400-3d8b-11e9-91a3-45b7914ac1aa.png)
![screen shot 2019-03-03 at 8 03 18 am](https://user-images.githubusercontent.com/48182222/53697928-2e6aa400-3d8b-11e9-9ca9-0fe50d96fa6c.png)
![screen shot 2019-03-03 at 8 03 34 am](https://user-images.githubusercontent.com/48182222/53697929-2e6aa400-3d8b-11e9-9ffc-2064af50764a.png)

**Comment by DieProgrammIDE** [comment]
You Probably did something wrong whilst compiling, it works out perfect for me. Perhaps, have you checked which Version of Xcode is installed. If you compile for tvOS13 it should be Xcode 11.x.

Did you try and click on Team and select your Name/Apple-ID, that seems to be a problem too.
If it fails to create a provisioning Profile first try and connect your Apple TV with your Computer with these steps: http://www.redmondpie.com/how-to-wirelessly-connect-apple-tv-4k-to-xcode-on-mac/ then select your Apple TV and then you can compile
