### ISSUE TITLE
problems with putting app to Apple TV

### ISSUE THREAD

**Issue by hartvd** [jvanakker/tvOSBrowser#23]
Hi, did every step there needed to be and works until I want to merge it to my new Apple TV 4K
Here Xcode give:
1. error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'Browser')
This while I gave my developer account into preferences of Xcode
2. error: No profiles for 'com.jva.tvbrowser' were found: Xcode couldn't find any tvOS App Development provisioning profiles matching 'com.jva.tvbrowser'. (in target 'Browser')
Don't know what that is.
Can you help me on this?

Great app by the way
thx

**Comment by cadetandrey** [comment]
Same problem

**Comment by hartvd** [comment]
Found out how, I needed to buy the developer account (99 dollar) and it works perfectly now

thx


SKKILLS
+32 (0) 50 64 10 14
info@skkills.com<mailto:hart@skkills.com>
www.skkills.com<http://www.skkills.com/>
 in<https://www.linkedin.com/company/skkills-your-technical-extension/>         ▶<https://www.youtube.com/channel/UCQYKiau-R3smF6SviAA-Mdg/>


Werken met Skkills? Bereken uw voordeel nu!<http://www.skkills.com/quote>



Op 10 mei 2019, om 13:28 heeft cadetandrey <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Same problem
