### ISSUE TITLE
iOS 13 beta

### ISSUE THREAD

**Issue by gionnidep** [jvanakker/tvOSBrowser#26]
It's possible to install on iOS 13 beta by using Xcode beta?

**Comment by danolga** [comment]
yes you need to modify in 

> Xcode-beta.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/Availability.h

the line 389 and 390 to:

>     #define __TVOS_UNAVAILABLE __OS_AVAILABILITY(tvos,unavailable)
>     #define __TVOS_PROHIBITED __OS_AVAILABILITY(tvos,unavailable)

after that you must set the proper deployment target and buildle identifier like this:

![image](https://user-images.githubusercontent.com/25048143/62808759-56f48800-baf9-11e9-887e-c4fe5912076f.png)

remeber change the team member in signs & capabilities

![image](https://user-images.githubusercontent.com/25048143/62808899-be123c80-baf9-11e9-9c41-76c25917fac7.png)

final result 
![Uploading image.png…]()

I hope this can help you

**Comment by jvanakker** [comment]
Thanks @danolga I've taken the liberty to use your instructional screenshots to update the main readme. There were an overwhelming number of people having issues by not setting the BundleID and team to their own.
