### ISSUE TITLE
Could not locate device support files tvOS 12.3

### ISSUE THREAD

**Issue by kelchert** [jvanakker/tvOSBrowser#29]
I am getting a successful build report, but then this message, "This Apple TV (4th generation) is running tvOS 12.3 (16M153), which may not be supported by this version of Xcode." in a dialogue with the black and white pinwheel next to the single button "Cancel Running". Any others of you, too? Thanks! 

— Kenn

**Comment by akoss** [comment]
You probably need to update to the latest version of Xcode.

**Comment by jvanakker** [comment]
Correct: if you see this message (for any iOS device) it means you need to update Xcode.
