### ISSUE TITLE
Any App in tvos 13 to browse the web ?

### ISSUE THREAD

**Issue by Woastscho** [jvanakker/tvOSBrowser#32]
I have an appleTV 4k und just updated to tvos 13.
I can't find any app to browse the web in tvos 13.
On earlier versions there was Safari, which worked fine.
I neither have a Mac or Xcode to install tvosBrowser.
Do you have any tips for me ?

**Comment by jvanakker** [comment]
Apple TV never officially had Safari.

Other than sideloading this 'hacky' app, your only solution is to use Airplay to show your broser from an iOS device on your Apple TV, by either using Airplay directly or using something like an app called AirBrowser.
