### ISSUE TITLE
Also working AppleTV 3?

### ISSUE THREAD

**Issue by highstone** [jvanakker/tvOSBrowser#33]
I stumbled upon this repository when researching a browser app for an Apple TV 3rd generation. Will this tvOSBrowser also work on older models? And if so, how to hook it up to my Mac...?

**Comment by luixiuno** [comment]
i got a jailbroken apple tv 3 and i am trying to get next.tweakboxapp.com in profiles but, the firmware wont even let me sideload apps via xcode

**Comment by jvanakker** [comment]
Sorry: only AppleTV of 4th generation (and up) run the modern Apple tvOS and up support custom apps. It's basically a completely different kind of OS compared to generations 1-3.
