### ISSUE TITLE
Property 'labelColor' not found on object of type 'UIColor'

### ISSUE THREAD

**Issue by Tron11** [jvanakker/tvOSBrowser#38]
return UIColor.labelColor;
This line is throwing an error on Xcode 10.1

Error code : Property 'labelColor' not found on object of type 'UIColor'

![Buildfail](https://user-images.githubusercontent.com/67714488/86295186-4e67dd00-bbf6-11ea-9672-516b41431c57.png)

**Comment by jvanakker** [comment]
Please update to at least Xcode 11.x or preferably the latest Xcode 12.x
