### ISSUE TITLE
'UIWebView' is unavailable: not available on tvOS

### ISSUE THREAD

**Issue by Akrastan** [jvanakker/tvOSBrowser#39]
Xcode Version 12.1 (12A7403) will not build tvBrowser for running on  Apple TV (4th generation) running tvOS 14.0.2 (18J411)

with this Sematic issue: UIWebView' is unavailable: not available on tvOS

Is there any runaround?

**Comment by jvanakker** [comment]
Make sure to use the latest version of the code.
