### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by nosadness8** [jvanakker/tvOSBrowser#41]
I need help with the build of tvOSBrowser on my Apple TV (tvOS 14.3, A1625 64GB) with XCode (Version 12.0.1 (12A7300)) via wifi. When I try to build to Apple TV (unplugged via wifi) fails with these error messages:

> No account for team "H7W77QXGX2". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

> No profiles for 'com.dreampiggy.tvbrowser' were found: Xcode couldn't find any tvOS App Development provisioning profiles matching 'com.dreampiggy.tvbrowser'.

What am I doing wrong? Can anyone help me, please?

**Comment by m-weller-de** [comment]
Hi,
Any updates for that?
I got the same error:

No profiles for 'com.dreampiggy.tvbrowser' were found: Xcode couldn't find any tvOS App Development provisioning profiles matching 'com.dreampiggy.tvbrowser'.

**Comment by davipt** [comment]
You need to setup your own bundle id and your own provision profiles. This is a generic step for any Xcode app development. There's also a duplicate issue already and a reply to the "issue": https://github.com/jvanakker/tvOSBrowser/issues/18#issuecomment-465502221

**Comment by m-weller-de** [comment]
Thanks!
